# Configurações compartilhadas por todos os microservices
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true      
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true

# ═══════════════════════════════════════════════════════════════════
# TRACING — Micrometer + OpenTelemetry
# ═══════════════════════════════════════════════════════════════════

management:
  server:
    port: null  # actuator porta padrão do serviço
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,traces
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
    prometheus:
      enabled: true
  tracing:
    sampling:
       probability: 1.0   # 100% das requisições rastreadas em dev
    export:
      zipkin:
        endpoint: http://localhost:9411/api/v2/spans   # Zipkin local (docker-compose.dev.yml)      
      
# LOG
logging:
  level:
    '[org.hibernate.SQL]': DEBUG
    '[org.hibernate.orm.jdbc.bind]': TRACE