server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/auth/**

            - id: catalog-books
              uri: lb://catalog-service
              predicates:
                - Path=/api/v1/books/**

            - id: catalog-authors
              uri: lb://catalog-service
              predicates:
                - Path=/api/v1/authors/**

            - id: catalog-categories
              uri: lb://catalog-service
              predicates:
                - Path=/api/v1/categories/**

            - id: loan-service
              uri: lb://loan-service
              predicates:
                - Path=/api/v1/loans/**

jwt:
  secret-key: dev-insecure-key-for-local-development-only-do-not-use-in-production

management:
  server:
    port: 8080

logging:
  level:
    '[com.example.gateway]': DEBUG
    '[org.springframework.cloud.gateway]': DEBUG