version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/library-api"      # ← atualizado
    schedule:
      interval: "weekly"
  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "docker"
    directory: "/library-api"      # ← atualizado
    schedule:
      interval: "weekly"