spring.jpa.open-in-view=true

application.mail.lateloans.message=Atenção! Você tem um empréstimo atrasado. Favor devolver o livro o mais rápido possível.
application.mail.default-remetent=mail@library-api.com

spring.mail.protocol=smtp
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=67f021ff50dd2b
spring.mail.password=91544df78a4228

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mvc.pathmatch.matching-strategy = ant-path-matcher