CREATE TABLE auth.tb_refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expiry_date TIMESTAMP WITH TIME ZONE,
    token VARCHAR(255) UNIQUE,
    user_id BIGINT,
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id)
        REFERENCES auth.tb_user (id) ON DELETE CASCADE
);

CREATE INDEX idx_refresh_token_user ON auth.tb_refresh_tokens(user_id);
CREATE INDEX idx_refresh_token_expiry ON auth.tb_refresh_tokens(expiry_date);
CREATE UNIQUE INDEX idx_refresh_token_unique ON auth.tb_refresh_tokens(token);