TRUNCATE TABLE tb_book RESTART IDENTITY CASCADE;
TRUNCATE TABLE tb_category RESTART IDENTITY CASCADE;
TRUNCATE TABLE tb_author RESTART IDENTITY CASCADE;
TRUNCATE TABLE tb_book_author RESTART IDENTITY CASCADE;
TRUNCATE TABLE tb_loan RESTART IDENTITY CASCADE;
TRUNCATE TABLE tb_user RESTART IDENTITY CASCADE;
TRUNCATE TABLE tb_loan_item RESTART IDENTITY CASCADE;
