-- ============================
-- Table: tb_user
-- ============================
CREATE TABLE tb_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    phone VARCHAR(20)
);

-- ============================
-- Table: tb_loan
-- ============================
CREATE TABLE tb_loan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_date DATE NOT NULL,
    due_date DATE NOT NULL,
    return_date DATE,
    status VARCHAR(30) NOT NULL,
    user_id BIGINT NOT NULL,

    CONSTRAINT fk_loan_user
        FOREIGN KEY (user_id)
        REFERENCES tb_user (id)
);

-- ============================
-- Table: tb_loan_item
-- ============================
CREATE TABLE tb_loan_item (
    loan_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,

    CONSTRAINT pk_loan_item
        PRIMARY KEY (loan_id, book_id),

    CONSTRAINT fk_loan_item_loan
        FOREIGN KEY (loan_id)
        REFERENCES tb_loan (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_loan_item_book
        FOREIGN KEY (book_id)
        REFERENCES tb_book (id)
);
