-- Migration: Create refresh_tokens table
-- Description: Stores refresh tokens for JWT authentication with proper indexes and constraints

-- =============================================
-- Ajuste do tipo da coluna status em tb_loan
-- =============================================

ALTER TABLE IF EXISTS tb_loan
    ALTER COLUMN status TYPE VARCHAR(255);

-- =============================================
-- Ajuste do tipo da coluna role em tb_user_roles
-- =============================================

ALTER TABLE IF EXISTS tb_user_roles
    ALTER COLUMN role TYPE VARCHAR(255);

-- =============================================
-- Criação da tabela tb_refresh_tokens
-- =============================================

CREATE TABLE IF NOT EXISTS tb_refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expiry_date TIMESTAMP WITH TIME ZONE,
    token VARCHAR(255) UNIQUE,
    user_id BIGINT
);

-- =============================================
-- Criação da Foreign Key
-- =============================================

ALTER TABLE IF EXISTS tb_refresh_tokens
    ADD CONSTRAINT fk_refresh_tokens_user
    FOREIGN KEY (user_id)
    REFERENCES tb_user (id)
    ON DELETE CASCADE;  -- Deletar tokens quando usuário é deletado
    
-- Índice no user_id (otimiza findByUser)
-- Permite buscar rapidamente todos os tokens de um usuário
CREATE INDEX idx_refresh_token_user 
	ON tb_refresh_tokens(user_id);

-- Índice composto para limpeza de tokens expirados
-- Otimiza query: DELETE FROM tb_refresh_tokens WHERE expiry_date < NOW()
CREATE INDEX idx_refresh_token_expiry 
	ON tb_refresh_tokens(expiry_date);

-- Comentários para documentação
COMMENT ON TABLE tb_refresh_tokens IS 'Stores JWT refresh tokens for token rotation strategy';
COMMENT ON COLUMN tb_refresh_tokens.token IS 'Unique refresh token (UUID-based, ~72 characters)';
COMMENT ON COLUMN tb_refresh_tokens.expiry_date IS 'Token expiration timestamp (configurable via jwt.refresh-token-days)';
COMMENT ON COLUMN tb_refresh_tokens.user_id IS 'User who owns this refresh token';