global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8091']

  - job_name: 'catalog-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8092']

  - job_name: 'loan-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8093']