-- ============================
-- Table: tb_category
-- ============================
CREATE TABLE tb_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

-- ============================
-- Table: tb_author
-- ============================
CREATE TABLE tb_author (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    biography TEXT
);

-- ============================
-- Table: tb_book
-- ============================
CREATE TABLE tb_book (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    isbn VARCHAR(20) NOT NULL UNIQUE,
    publication_year INTEGER,
    available_copies INTEGER,
    category_id BIGINT NOT NULL,

    FOREIGN KEY (category_id) REFERENCES tb_category(id)
);

-- ============================
-- Table: tb_book_author
-- ============================
CREATE TABLE tb_book_author (
    book_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,

    CONSTRAINT pk_book_author
        PRIMARY KEY (book_id, author_id),

    CONSTRAINT fk_book_author_book
        FOREIGN KEY (book_id)
        REFERENCES tb_book (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_book_author_author
        FOREIGN KEY (author_id)
        REFERENCES tb_author (id)
        ON DELETE CASCADE
);
