server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        native:
          search-locations: file:../config-repo   # ← lê os YAMLs da pasta config-repo/
      label: main

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  endpoint:
    health:
      show-details: always