CREATE TABLE lending.tb_loan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_date DATE NOT NULL,
    due_date DATE NOT NULL,
    return_date DATE,
    status VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    created_by VARCHAR(255),
    last_modified_by VARCHAR(255),
    version BIGINT DEFAULT 0
);

CREATE TABLE lending.tb_loan_item (
    loan_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    created_by VARCHAR(255),
    last_modified_by VARCHAR(255),
    version BIGINT DEFAULT 0,
    CONSTRAINT pk_loan_item PRIMARY KEY (loan_id, book_id),
    CONSTRAINT fk_loan_item_loan FOREIGN KEY (loan_id)
        REFERENCES lending.tb_loan(id) ON DELETE CASCADE
);